const DEFAULT_FILAMENT_DIAMETER_MM = 1.75;
const DEFAULT_DENSITY_G_PER_CM3 = 1.24;
const METADATA_SCAN_LINES = 200;
const SLICER_SCAN_LINES = 50;

function splitValues(raw) {
  if (!raw) {
    return [];
  }

  return raw
    .split(/[;,]/)
    .map((value) => value.trim())
    .filter(Boolean);
}

function parseNumber(value) {
  if (typeof value !== 'string') {
    return Number.NaN;
  }

  const normalized = value.trim().replace(',', '.');
  const parsed = Number.parseFloat(normalized);
  return Number.isFinite(parsed) ? parsed : Number.NaN;
}

function parseNumberList(raw) {
  return splitValues(raw)
    .map(parseNumber)
    .filter((value) => Number.isFinite(value));
}

function metersToGrams(meters) {
  if (!Number.isFinite(meters) || meters <= 0) {
    return 0;
  }

  const radiusMm = DEFAULT_FILAMENT_DIAMETER_MM / 2;
  const areaMm2 = Math.PI * radiusMm * radiusMm;
  const lengthMm = meters * 1000;
  const volumeMm3 = areaMm2 * lengthMm;
  const volumeCm3 = volumeMm3 / 1000;
  return volumeCm3 * DEFAULT_DENSITY_G_PER_CM3;
}

function parseDurationToHours(raw) {
  if (!raw) {
    return null;
  }

  const value = String(raw).trim().toLowerCase();
  if (!value) {
    return null;
  }

  let totalSeconds = 0;

  const hourMatch = value.match(/(\d+(?:[.,]\d+)?)\s*h(?:ours?)?/i);
  if (hourMatch) {
    totalSeconds += parseNumber(hourMatch[1]) * 3600;
  }

  const minuteMatch = value.match(/(\d+(?:[.,]\d+)?)\s*m(?:in(?:utes?)?)?/i);
  if (minuteMatch) {
    totalSeconds += parseNumber(minuteMatch[1]) * 60;
  }

  const secondMatch = value.match(/(\d+(?:[.,]\d+)?)\s*s(?:ec(?:onds?)?)?/i);
  if (secondMatch) {
    totalSeconds += parseNumber(secondMatch[1]);
  }

  if (totalSeconds > 0) {
    return totalSeconds / 3600;
  }

  const fallback = parseNumber(value);
  if (Number.isFinite(fallback) && fallback > 0) {
    return fallback / 3600;
  }

  return null;
}

function detectSlicer(headerLines) {
  for (const line of headerLines) {
    const trimmed = line.trim();
    if (!/^;\s*generated by\s+/i.test(trimmed)) {
      continue;
    }

    const normalized = trimmed.toLowerCase();
    if (normalized.includes('orcaslicer')) {
      return 'OrcaSlicer';
    }
    if (normalized.includes('bambustudio')) {
      return 'BambuStudio';
    }
    if (normalized.includes('superslicer')) {
      return 'SuperSlicer';
    }
    if (normalized.includes('prusaslicer')) {
      return 'PrusaSlicer';
    }
    if (normalized.includes('cura')) {
      return 'Cura';
    }
  }

  return null;
}

function buildMetadataLines(lines) {
  if (lines.length <= METADATA_SCAN_LINES * 2) {
    return lines;
  }

  return [
    ...lines.slice(0, METADATA_SCAN_LINES),
    ...lines.slice(lines.length - METADATA_SCAN_LINES),
  ];
}

function ensureExtruder(extrudersMap, index) {
  const key = Number.isFinite(index) && index >= 0 ? index : 0;

  if (!extrudersMap.has(key)) {
    extrudersMap.set(key, {
      index: key,
      filamentType: null,
      color: null,
      usageMeters: 0,
      usageGrams: 0,
      gramsFromDirectMetadata: false,
    });
  }

  return extrudersMap.get(key);
}

function applyListToExtruders(extrudersMap, values, setter) {
  for (let index = 0; index < values.length; index += 1) {
    const entry = ensureExtruder(extrudersMap, index);
    setter(entry, values[index]);
  }
}

function parseTimeFromLine(line) {
  let parsed = null;

  const timeGhostMatch = line.match(/^;\s*time_ghost\s*[:=]\s*(\d+(?:[.,]\d+)?)/i);
  if (timeGhostMatch) {
    const seconds = parseNumber(timeGhostMatch[1]);
    if (Number.isFinite(seconds)) {
      parsed = seconds / 3600;
    }
  }

  const timeSecondsMatch = line.match(/^;\s*time\s*[:=]\s*(\d+(?:[.,]\d+)?)/i);
  if (timeSecondsMatch) {
    const seconds = parseNumber(timeSecondsMatch[1]);
    if (Number.isFinite(seconds)) {
      parsed = seconds / 3600;
    }
  }

  const printTimeMatch = line.match(/^;\s*print\s*time\s*[:=]\s*(.+)$/i);
  if (printTimeMatch) {
    const hours = parseDurationToHours(printTimeMatch[1]);
    if (Number.isFinite(hours)) {
      parsed = hours;
    }
  }

  const estimatedTimeMatch = line.match(
    /^;\s*estimated\s+printing\s+time(?:\s*\([^)]*\))?\s*[:=]\s*(.+)$/i
  );
  if (estimatedTimeMatch) {
    const hours = parseDurationToHours(estimatedTimeMatch[1]);
    if (Number.isFinite(hours)) {
      parsed = hours;
    }
  }

  return parsed;
}

function parseFilamentFromLine(line, extrudersMap, usageHints) {
  const filamentMetersMatch = line.match(/^;\s*filament\s+used\s*[:=]\s*(.+)$/i);
  if (filamentMetersMatch) {
    const values = splitValues(filamentMetersMatch[1])
      .map((value) => {
        const meterMatch = value.match(/(\d+(?:[.,]\d+)?)\s*m\b/i);
        return meterMatch ? parseNumber(meterMatch[1]) : Number.NaN;
      })
      .filter((value) => Number.isFinite(value));

    applyListToExtruders(extrudersMap, values, (entry, meters) => {
      entry.usageMeters = Math.max(entry.usageMeters, meters);
      usageHints.hasAnyUsage = true;
      if (!entry.gramsFromDirectMetadata) {
        entry.usageGrams = Math.max(entry.usageGrams, metersToGrams(meters));
      }
    });
  }

  const filamentMmMatch = line.match(/^;\s*filament\s+used\s*\[mm\]\s*[:=]\s*(.+)$/i);
  if (filamentMmMatch) {
    const valuesMm = parseNumberList(filamentMmMatch[1]);
    applyListToExtruders(extrudersMap, valuesMm, (entry, mm) => {
      const meters = mm / 1000;
      entry.usageMeters = Math.max(entry.usageMeters, meters);
      usageHints.hasAnyUsage = true;
      if (!entry.gramsFromDirectMetadata) {
        entry.usageGrams = Math.max(entry.usageGrams, metersToGrams(meters));
      }
    });
  }

  const totalGramsMatch = line.match(/^;\s*total\s+filament\s+used\s*\[g\]\s*[:=]\s*(.+)$/i);
  if (totalGramsMatch) {
    const grams = parseNumber(totalGramsMatch[1]);
    if (Number.isFinite(grams) && grams > 0) {
      usageHints.totalGramsFromSummary = grams;
      usageHints.hasAnyUsage = true;
    }
  }

  const filamentGramsMatch = line.match(/^;\s*filament\s+used\s*\[g\]\s*[:=]\s*(.+)$/i);
  if (filamentGramsMatch) {
    const values = parseNumberList(filamentGramsMatch[1]);
    applyListToExtruders(extrudersMap, values, (entry, grams) => {
      entry.usageGrams = Math.max(entry.usageGrams, grams);
      entry.gramsFromDirectMetadata = true;
      usageHints.hasAnyUsage = true;
    });
  }
}

function parseExtruderMetaFromLine(line, extrudersMap, usageHints) {
  const filamentTypeMatch = line.match(/^;\s*filament_type\s*[:=]\s*(.+)$/i);
  if (filamentTypeMatch) {
    const values = splitValues(filamentTypeMatch[1]);
    applyListToExtruders(extrudersMap, values, (entry, type) => {
      entry.filamentType = type || null;
    });
  }

  const filamentColorMatch = line.match(/^;\s*filament_?colou?r\s*[:=]\s*(.+)$/i);
  if (filamentColorMatch) {
    const values = splitValues(filamentColorMatch[1]);
    applyListToExtruders(extrudersMap, values, (entry, color) => {
      entry.color = color || null;
    });
  }

  const extruderColorMatch = line.match(/^;\s*extruder_?colou?r\s*[:=]\s*(.+)$/i);
  if (extruderColorMatch) {
    const values = splitValues(extruderColorMatch[1]);
    applyListToExtruders(extrudersMap, values, (entry, color) => {
      entry.color = color || null;
    });
  }

  const extruderTrainMatch = line.match(/^;\s*extruder_train\.(\d+)\.initial\.temperature\s*[:=]/i);
  if (extruderTrainMatch) {
    const index = Number.parseInt(extruderTrainMatch[1], 10);
    if (Number.isInteger(index) && index >= 0) {
      ensureExtruder(extrudersMap, index);
    }
  }

  const standaloneUsageMatch = line.match(/^;\s*filament\s+used\s*[:=]\s*(\d+(?:[.,]\d+)?)\s*m\b/i);
  if (standaloneUsageMatch) {
    usageHints.hasAnyUsage = true;
  }
}

function finalizeExtruders(extrudersMap, usageHints) {
  let extruders = Array.from(extrudersMap.values())
    .sort((a, b) => a.index - b.index)
    .map((entry) => ({
      index: entry.index,
      filamentType: entry.filamentType,
      color: entry.color,
      usageMeters: Number.isFinite(entry.usageMeters) ? entry.usageMeters : 0,
      usageGrams: Number.isFinite(entry.usageGrams) ? entry.usageGrams : 0,
    }));

  if (extruders.length === 0 && usageHints.hasAnyUsage) {
    const grams = Number.isFinite(usageHints.totalGramsFromSummary)
      ? usageHints.totalGramsFromSummary
      : 0;
    extruders = [
      {
        index: 0,
        filamentType: null,
        color: null,
        usageMeters: 0,
        usageGrams: grams,
      },
    ];
  }

  let totalGrams = extruders.reduce((sum, item) => sum + item.usageGrams, 0);

  if (Number.isFinite(usageHints.totalGramsFromSummary) && usageHints.totalGramsFromSummary > totalGrams) {
    if (extruders.length === 0) {
      extruders = [
        {
          index: 0,
          filamentType: null,
          color: null,
          usageMeters: 0,
          usageGrams: usageHints.totalGramsFromSummary,
        },
      ];
    } else if (extruders.length === 1) {
      extruders[0].usageGrams = usageHints.totalGramsFromSummary;
    }

    totalGrams = extruders.reduce((sum, item) => sum + item.usageGrams, 0);
  }

  return { extruders, totalGrams };
}

/**
 * Parse G-code metadata from raw text.
 * @param {string} text Raw G-code text.
 * @returns {{ estimatedHours: number, extruders: Array<{ index: number, filamentType: string | null, color: string | null, usageMeters: number, usageGrams: number }>, totalGrams: number, slicer: string | null }}
 */
export function parseGCode(text) {
  if (typeof text !== 'string' || text.length === 0) {
    return {
      estimatedHours: 0,
      extruders: [],
      totalGrams: 0,
      slicer: null,
    };
  }

  const lines = text.split(/\r?\n/);
  const slicer = detectSlicer(lines.slice(0, SLICER_SCAN_LINES));
  const metadataLines = buildMetadataLines(lines);

  const extrudersMap = new Map();
  const usageHints = {
    hasAnyUsage: false,
    totalGramsFromSummary: null,
  };

  let estimatedHours = 0;

  for (const line of metadataLines) {
    const parsedHours = parseTimeFromLine(line);
    if (Number.isFinite(parsedHours) && parsedHours >= 0) {
      estimatedHours = parsedHours;
    }

    parseFilamentFromLine(line, extrudersMap, usageHints);
    parseExtruderMetaFromLine(line, extrudersMap, usageHints);
  }

  const { extruders, totalGrams } = finalizeExtruders(extrudersMap, usageHints);

  return {
    estimatedHours: Number.isFinite(estimatedHours) ? estimatedHours : 0,
    extruders,
    totalGrams: Number.isFinite(totalGrams) ? totalGrams : 0,
    slicer,
  };
}
