import { describe, expect, it } from 'vitest';
import { parseGCode } from '../gcodeParser';

const gramsFromMeters = (meters) => meters * Math.PI * (0.875 ** 2) * 1.24;

describe('parseGCode', () => {
  describe('empty/invalid input', () => {
    it('returns safe defaults for empty string', () => {
      expect(parseGCode('')).toEqual({
        estimatedHours: 0,
        extruders: [],
        totalGrams: 0,
        slicer: null,
      });
    });

    it('returns safe defaults for null without throwing', () => {
      expect(() => parseGCode(null)).not.toThrow();
      expect(parseGCode(null)).toEqual({
        estimatedHours: 0,
        extruders: [],
        totalGrams: 0,
        slicer: null,
      });
    });

    it('returns safe defaults for undefined without throwing', () => {
      expect(() => parseGCode(undefined)).not.toThrow();
      expect(parseGCode(undefined)).toEqual({
        estimatedHours: 0,
        extruders: [],
        totalGrams: 0,
        slicer: null,
      });
    });

    it('returns zeros when no metadata comments are present', () => {
      const text = [
        'G21',
        'G90',
        'M82',
        'G1 X100 Y100 F3000',
        'G1 X120 Y120 E1.23',
      ].join('\n');

      expect(parseGCode(text)).toEqual({
        estimatedHours: 0,
        extruders: [],
        totalGrams: 0,
        slicer: null,
      });
    });
  });

  describe('slicer detection', () => {
    it('detects OrcaSlicer', () => {
      const result = parseGCode('; Generated by OrcaSlicer 2.0');
      expect(result.slicer).toBe('OrcaSlicer');
    });

    it('detects BambuStudio', () => {
      const result = parseGCode('; generated by BambuStudio');
      expect(result.slicer).toBe('BambuStudio');
    });

    it('detects PrusaSlicer', () => {
      const result = parseGCode('; Generated by PrusaSlicer');
      expect(result.slicer).toBe('PrusaSlicer');
    });

    it('detects SuperSlicer', () => {
      const result = parseGCode('; Generated by SuperSlicer');
      expect(result.slicer).toBe('SuperSlicer');
    });

    it('detects Cura from Cura_SteamEngine', () => {
      const result = parseGCode('; Generated by Cura_SteamEngine');
      expect(result.slicer).toBe('Cura');
    });

    it('returns null when generated by line is missing', () => {
      const result = parseGCode('; printer profile: Generic');
      expect(result.slicer).toBeNull();
    });
  });

  describe('print time parsing', () => {
    it('parses TIME seconds to hours', () => {
      const result = parseGCode(';TIME:3600');
      expect(result.estimatedHours).toBe(1);
    });

    it('parses TIME with non-integer hour result', () => {
      const result = parseGCode(';TIME:5400');
      expect(result.estimatedHours).toBe(1.5);
    });

    it('parses TIME_GHOST seconds to hours', () => {
      const result = parseGCode(';TIME_GHOST:7200');
      expect(result.estimatedHours).toBe(2);
    });

    it('parses estimated printing time format', () => {
      const result = parseGCode('; estimated printing time (normal mode) = 2h 30m 0s');
      expect(result.estimatedHours).toBeCloseTo(2.5, 6);
    });

    it('parses Print time with min token', () => {
      const result = parseGCode('; Print time: 1h 15min');
      expect(result.estimatedHours).toBeCloseTo(1.25, 6);
    });

    it('uses the last time value found', () => {
      const result = parseGCode([
        ';TIME:1800',
        ';TIME_GHOST:3600',
        '; estimated printing time (normal mode) = 2h 30m 0s',
      ].join('\n'));

      expect(result.estimatedHours).toBeCloseTo(2.5, 6);
    });
  });

  describe('filament usage (meters to grams)', () => {
    it('parses single extruder meters and computes grams', () => {
      const result = parseGCode(';Filament used: 1.5m');

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageMeters).toBe(1.5);
      expect(result.extruders[0].usageGrams).toBeGreaterThan(0);
      expect(result.extruders[0].usageGrams).toBeCloseTo(gramsFromMeters(1.5), 3);
      expect(result.totalGrams).toBeCloseTo(gramsFromMeters(1.5), 3);
    });

    it('parses multi-extruder meter values', () => {
      const result = parseGCode(';Filament used: 2.0m, 1.0m');

      expect(result.extruders).toHaveLength(2);
      expect(result.extruders[0].usageMeters).toBe(2);
      expect(result.extruders[1].usageMeters).toBe(1);
      expect(result.extruders[0].usageGrams).toBeCloseTo(gramsFromMeters(2), 3);
      expect(result.extruders[1].usageGrams).toBeCloseTo(gramsFromMeters(1), 3);
    });

    it('parses filament used [mm] as meters', () => {
      const result = parseGCode('; filament used [mm] = 1500');

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageMeters).toBe(1.5);
      expect(result.extruders[0].usageGrams).toBeCloseTo(gramsFromMeters(1.5), 3);
    });
  });

  describe('filament usage (direct grams)', () => {
    it('uses direct grams for single extruder', () => {
      const result = parseGCode('; filament used [g] = 25.5');

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageGrams).toBe(25.5);
      expect(result.totalGrams).toBe(25.5);
    });

    it('uses direct grams for multiple extruders', () => {
      const result = parseGCode('; filament used [g] = 25.5;12.3');

      expect(result.extruders).toHaveLength(2);
      expect(result.extruders[0].usageGrams).toBe(25.5);
      expect(result.extruders[1].usageGrams).toBe(12.3);
      expect(result.totalGrams).toBeCloseTo(37.8, 6);
    });

    it('uses total filament used [g] summary when larger than parsed total', () => {
      const result = parseGCode('; total filament used [g] = 37.8');

      expect(result.totalGrams).toBeGreaterThanOrEqual(37.8);
      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageGrams).toBe(37.8);
    });

    it('keeps direct grams over meter-based estimates', () => {
      const result = parseGCode([
        '; filament used [mm] = 5000',
        '; filament used [g] = 15.2',
      ].join('\n'));

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageMeters).toBe(5);
      expect(result.extruders[0].usageGrams).toBe(15.2);
      expect(result.totalGrams).toBe(15.2);
    });
  });

  describe('filament type and color', () => {
    it('parses filament type for one extruder', () => {
      const result = parseGCode('; filament_type = PLA');

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].filamentType).toBe('PLA');
    });

    it('parses filament type for multiple extruders', () => {
      const result = parseGCode('; filament_type = PLA;PETG');

      expect(result.extruders).toHaveLength(2);
      expect(result.extruders[0].filamentType).toBe('PLA');
      expect(result.extruders[1].filamentType).toBe('PETG');
    });

    it('parses filament colour for multiple extruders', () => {
      const result = parseGCode('; filament_colour = #FFFFFF;#000000');

      expect(result.extruders).toHaveLength(2);
      expect(result.extruders[0].color).toBe('#FFFFFF');
      expect(result.extruders[1].color).toBe('#000000');
    });

    it('parses extruder_colour', () => {
      const result = parseGCode('; extruder_colour = #FF0000');

      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].color).toBe('#FF0000');
    });
  });

  describe('multi-extruder full scenario', () => {
    it('parses a realistic BambuStudio multi-extruder header', () => {
      const text = [
        '; generated by BambuStudio',
        '; filament_type = PLA;PETG',
        '; filament_colour = #FFFFFF;#FF0000',
        '; filament used [g] = 20.5;8.3',
        '; estimated printing time (normal mode) = 3h 15m 0s',
      ].join('\n');

      const result = parseGCode(text);

      expect(result.slicer).toBe('BambuStudio');
      expect(result.estimatedHours).toBeCloseTo(3.25, 6);
      expect(result.extruders).toHaveLength(2);
      expect(result.extruders[0]).toMatchObject({
        index: 0,
        filamentType: 'PLA',
        color: '#FFFFFF',
        usageGrams: 20.5,
      });
      expect(result.extruders[1]).toMatchObject({
        index: 1,
        filamentType: 'PETG',
        color: '#FF0000',
        usageGrams: 8.3,
      });
      expect(result.totalGrams).toBeCloseTo(28.8, 6);
    });
  });

  describe('large file metadata scan (header + footer)', () => {
    it('extracts metadata from first and last scan windows only', () => {
      const header = [
        '; generated by OrcaSlicer 2.1',
        ';TIME:3600',
        '; filament_type = PLA',
      ];

      const middle = Array.from({ length: 450 }, (_, index) => `G1 X${index} Y${index} F3000`);

      const footer = [
        '; filament used [g] = 11.5',
        '; Print time: 2h 0m 0s',
      ];

      const text = [...header, ...middle, ...footer].join('\n');
      const result = parseGCode(text);

      expect(text.split(/\r?\n/)).toHaveLength(455);
      expect(result.slicer).toBe('OrcaSlicer');
      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].filamentType).toBe('PLA');
      expect(result.extruders[0].usageGrams).toBe(11.5);
      expect(result.totalGrams).toBe(11.5);
      expect(result.estimatedHours).toBe(2);
    });
  });

  describe('complete slicer-style examples', () => {
    it('parses Cura-style complete metadata', () => {
      const text = [
        ';Generated by Cura_SteamEngine 5.0',
        ';TIME:7200',
        ';Filament used: 3.5m',
        ';EXTRUDER_TRAIN.0.INITIAL.TEMPERATURE:200',
      ].join('\n');

      const result = parseGCode(text);

      expect(result.slicer).toBe('Cura');
      expect(result.estimatedHours).toBe(2);
      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].index).toBe(0);
      expect(result.extruders[0].usageMeters).toBe(3.5);
      expect(result.extruders[0].usageGrams).toBeCloseTo(gramsFromMeters(3.5), 3);
      expect(result.totalGrams).toBeCloseTo(gramsFromMeters(3.5), 3);
    });

    it('parses PrusaSlicer-style complete metadata and prefers grams over mm', () => {
      const text = [
        '; generated by PrusaSlicer 2.7',
        '; filament used [mm] = 5000',
        '; filament used [g] = 15.2',
        '; estimated printing time (normal mode) = 1h 45m 30s',
      ].join('\n');

      const result = parseGCode(text);

      expect(result.slicer).toBe('PrusaSlicer');
      expect(result.estimatedHours).toBeCloseTo(1.7583333333, 6);
      expect(result.extruders).toHaveLength(1);
      expect(result.extruders[0].usageMeters).toBe(5);
      expect(result.extruders[0].usageGrams).toBe(15.2);
      expect(result.totalGrams).toBe(15.2);
    });
  });
});
